### PR TITLE
Allow to overwrite if input is highlighted

### PR DESCRIPTION
**Pull request by lreindl**

### CODE REVIEW

**Comment by rwaltenberg** [comment]
Hi @lreindl, that's a great idea! Have you extensively tested it?

**Comment by rwaltenberg** [comment]
Hi @lreindl, that's a great idea! Have you extensively tested it?

**Comment by lreindl** [comment]
@rwaltenberg I did usability testing but I haven't written any tests. I am currently using this in production.

**Comment by rwaltenberg** [comment]
That's enough for me. Merging. Thanks!

**Pull request merged**
